[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remmappings = [
    '@openzeppeling/contracts=lib/openzeppelin-contracts/contracts'
]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./img" } 
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
